Add OpenAPI 3 Schema using drf-spectacular
nexB/scancode.io pull request #107
Opened 2021-03-06 17:15 UTC by hanif-ali

Adds a Swagger schema accessible through the navigation bar. I think adding this would help us document the API in a standardized manner. I went with `drf-spectacular` because it was being used in vulnerablecode already and provides more extensibility than the alternatives.

closes #106

2021-03-08 14:27 UTC, hanif-ali commented
@tdruez Please review this.

2021-03-18 19:09 UTC, majurg requested changes

2021-03-18 19:09 UTC, majurg commented on scancodeio/urls.py
> +    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(), name="swagger-ui"),
Would the swaggerUI only effect these schema endpoints?

2021-03-18 19:09 UTC, majurg commented on scanner/models.py
> +    def status(self) -> str:
Not sure we want to mix and match type annotations. We should probably remove this.

2021-03-18 19:09 UTC, majurg commented on scanpipe/api/serializers.py
> +    def get_codebase_resources_summary(self, project) -> dict:
Not sure we want to mix and match type annotations. We should probably remove this.

2021-03-18 19:09 UTC, majurg commented on scanpipe/api/serializers.py
> +    def get_discovered_package_summary(self, project) -> dict:
Not sure we want to mix and match type annotations. We should probably remove this.

2021-03-18 19:09 UTC, majurg commented on scanpipe/models.py
> +    def execution_time(self) -> int:
Not sure we want to mix and match type annotations. We should probably remove this.

2021-03-18 19:09 UTC, majurg commented on scanpipe/models.py
> +    def input_root(self) -> list:
Not sure we want to mix and match type annotations. We should probably remove this.

2021-03-18 19:09 UTC, majurg commented on scanpipe/models.py
> +    def output_root(self) -> list:
Not sure we want to mix and match type annotations. We should probably remove this.

2021-07-21 06:08 UTC, pombredanne commented
@hanif-ali gentle ping... are you planning to finish this? Otherwise we may close it for now.

2021-09-01 05:26 UTC, closed without merging