Project Name cleanup
nexB/scancode.io pull request #158
Opened 2021-04-22 15:43 UTC by AvishrantsSh

Includes fix for #117 along with unittest.

2021-04-26 10:20 UTC, tdruez requested changes
Thanks for the PR, see my comments to improve the code before the merge.

2021-04-26 10:20 UTC, tdruez commented on scanpipe/tests/test_forms.py
> +        )
There's no need for mock here, we are only testing the name cleanup, you can remove the "input_urls" from the input data to simplify this test.

2021-04-26 10:20 UTC, tdruez commented on scanpipe/tests/test_forms.py
> +        self.assertEqual("Test Name", form.cleaned_data["name"])
It would be nice to save() the form and load the new project from the database to ensure the "saved "name was properly cleaned as well.

2021-04-28 08:12 UTC, merged

2021-04-28 08:25 UTC, tdruez commented
@AvishrantsSh thanks again for the PR.

Couple comments to improve your contributions to open source in general:
- Add a "sign off" in your commits message, like `Signed-off-by: Avishrant Sharma <avishrants@gmail.com>`
- Avoid to mix upper and lower case randomly on words, for example "Project Name Cleansed before Saving" is more readable as "Project name cleansed before saving"

See https://aboutcode.readthedocs.io/en/latest/contributing/writing_good_commit_messages.html for more on commit messages.

2021-04-28 08:58 UTC, AvishrantsSh commented
@tdruez thanks for the tips, I'll keep them in mind.