Improve scancodeio installation documentation #167
nexB/scancode.io pull request #183
Opened 2021-05-27 19:59 UTC by hyounes4560

This PR: 

- Improve the ScanCode.io installation documentation #167  

Please note that I am not able to run scripts locally to check for any errors or broken links

Signed-off-by: Hanan Younes <hyounes4560@conestogac.on.ca>

2021-05-28 15:18 UTC, tdruez requested changes
@hyounes4560 Thanks for those improvements to the docs, looks great.
See my minor comments for requested changes.

2021-05-28 15:18 UTC, tdruez commented on docs/installation.rst
> +* Inside the ScanCode folder, install the required dependencies::
"Inside the ``scancode.io/`` directory, ..."

2021-05-28 15:19 UTC, tdruez commented
> @hyounes4560 Please note that I am not able to run scripts locally to check for any errors or broken links

You mean you cannot compile the documentation locally on your machine?

2021-05-28 15:47 UTC, AyanSinhaMahapatra commented
So @tdruez I think she means that she has buuld the documentation locally but can't run linter checks etc via scripts as in skeleton/other repos. https://github.com/nexB/scancode-toolkit/tree/develop/docs/scripts 

So I was wondering if we could add a github actions in scancode.io with the doc build and linter checks in a github action like we have [here](https://github.com/nexB/scancode-analyzer/blob/main/.github/workflows/ci-docs.yml) ? Would that be an okay thing to add? I guess now the doc builds are not checked for build errors or linted in scancode.io?

2021-05-28 15:53 UTC, AyanSinhaMahapatra requested changes

2021-05-28 15:53 UTC, AyanSinhaMahapatra commented on docs/installation.rst
> +    ScanCode.io can **ONLY** be run on Windows through `Docker <https://www.docker.com/>`_ or `Virtual Machines <https://www.virtualbox.org/>`_. However, to avoid any installation issues, it is **NOT
`**NOT RECOMMEND**` should really be `*Not Recommended*` ? Avoid all caps, use the [inline markups here](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#inline-markup) only, consistently across documentation.

2021-06-01 12:09 UTC, tdruez approved these changes
@hyounes4560 thanks again for the documentation improvements!

@AyanSinhaMahapatra I'll add the docs linter in the CI, thanks for the input.

2021-06-01 12:10 UTC, merged