added docker-compose requirement to [Run With Docker]
nexB/scancode.io pull request #585
Opened 2023-01-13 12:17 UTC by OctoPie23

This PR fixes #584 by adding:
 - docker-compose to the **installation.rst** installation file guide.
 - change all the `docker compose` to `docker-compose` 

Signed-off-by: OctoPie23 <coveringguy0123@gmail.com>

2023-01-14 03:24 UTC, OctoPie23 commented
@pombredanne Can you look into this small documentation change?

2023-01-15 19:25 UTC, pombredanne requested changes
Thank you ... but there are some issues with this seemingly tiny doc change ... It would need to be improved.

2023-01-15 19:25 UTC, pombredanne commented on docs/installation.rst
> +    apt install docker-compose
We are not supporting only Linux and only Debian-based distros. We have two ways to deal with this. We can use docker-compose 1.x which is a Python package or the docker-compose 2.x which is a single executable is Go.

2023-01-15 19:25 UTC, pombredanne commented on docs/installation.rst
> +    docker-compose up
You are likely assuming this is using docker-compose 2.x?

2023-01-16 06:26 UTC, OctoPie23 commented
Oh, I'm sorry🤦‍♂️. I got confused.
I had downloaded the docker-compose 1.x version, therefore the command `docker compose` was returning the error `compose: command not found`.
Would it be possible to refer to the [Manual Installation](https://docs.docker.com/compose/install/linux/#install-the-plugin-manually) in case someone encounters a problem?
Else
We could probably just close this PR.

2023-02-15 09:53 UTC, closed without merging