fix: update rootfs to scan resource path
nexB/scancode.io pull request #840
Opened 2023-08-01 21:24 UTC by philcali

When uploading an exported Linux rootfs archive, the current rootfs included the extracted root directory, which broke linking files from installed packages, (ie: rpms.sqlite). This change fixes that.

2023-08-02 06:41 UTC, pombredanne commented
Thanks! 
Do you mind you amend your commit with a DCS signoff?

2023-08-02 13:35 UTC, philcali commented
Will do.

2023-08-05 12:14 UTC, pombredanne requested changes
This is looking great!
Thanks.
I submitted https://github.com/philcali/scancode.io/pull/1 so you get the latest main and we would need a simple CHANGELOG entry here to merge this PR

2023-08-07 13:18 UTC, philcali commented
Thank you! Changelog entry was added.

2023-08-07 14:34 UTC, merged